image: "rust:latest"
cache:
  paths:
    - target/

stages:
  - test
  - publish

before_script:
  - "chmod u+x ./ci-setup.sh"
  - "./ci-setup.sh"

tests:
  stage: test
  environment:
    name: test
  script:
    - "cargo test -- --nocapture"

cratesio:
  stage: publish
  script:
    - echo "Nothing!"
  only:
    - prod
