image: "rust:stable"

stages:
  - test
  - publish

tests:
  stage: test
  script:
    - "chmod u+x ./ci-setup.sh"
    - "./ci-setup.sh"
    - "RUST_LOG=get_sig_from_timsdk=trace,tls_sig_api=trace"
    - "cargo test -- --nocapture"

cratesio:
  stage: publish
  script:
    - echo "Nothing!"
  only:
    - prod
