image: "rust:latest"
cache:
  paths:
    - target/

stages:
  - test
  - publish

before_script:
  - "chmod u+x ./ci-setup.sh"
  - "./ci-setup.sh"

tests:
  stage: test
  environment:
    name: test
  script:
    - "cargo test -- --nocapture"

cratesio prepublish check:
  stage: publish
  environment:
    name: cratesio
  script:
    - cargo login $CARGO_TOKEN
    - cargo publish --dry-run
  only:
    - prod

cratesio:
  stage: publish
  environment:
    name: cratesio
  script:
    - cargo login $CARGO_TOKEN
    - cargo publish
  only:
    branches:
      - prod
    tags:
      - /^v(0|([1-9]\d+))\.(0|([1-9]\d+))\.(0|([1-9]\d+))$/
