image: "rust:latest"
cache:
  paths:
    - target/

stages:
  - test
  - publish

tests:
  before_script:
    - "chmod u+x ./ci-setup.sh"
    - "./ci-setup.sh"
  stage: test
  environment:
    name: test
  script:
    - "cargo test -- --nocapture"

cratesio prepublish check:
  stage: publish
  environment:
    name: cratesio
  script:
    - cargo login $CARGO_TOKEN
    - cargo publish --dry-run
  only:
    - prod
